from django.test import TestCase

from LetsCook.profiles.models import Profile
from tests.base.testing_utils.create_user_objects import create_regular_user


class ProfileModelTest(TestCase):
    def test_profileInit_withUserCreation(self):
        user = create_regular_user()
        profile = user.profile
        profile_db = Profile.objects.first()
        self.assertEqual(profile_db.pk, profile.pk)
        # profile username should be autogenerated from the user email
        self.assertIn(profile.username, user.email)
        self.assertEqual('', profile.first_name)
        self.assertEqual('', profile.last_name)
        self.assertFalse(profile.dark_theme)
