# Generated by Django 3.2.5 on 2021-07-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_icook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icookuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
