# Generated by Django 3.2.5 on 2021-07-07 19:25
from django.contrib.postgres.operations import HStoreExtension

import LetsCook.core.validators
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), LetsCook.core.validators.validate_digits_not_in_string])),
                ('image', models.ImageField(blank=True, upload_to='recipes')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('servings', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ingredients', django.contrib.postgres.fields.hstore.HStoreField()),
                ('preparation', models.TextField(max_length=1000)),
                ('vegetarian', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
