# Generated by Django 3.2.5 on 2021-07-19 21:12

import LetsCook.core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('breakfast', 'breakfast'), ('salad', 'salad'), ('soup', 'soup'), ('appetizer', 'appetizer'), ('main', 'main'), ('dessert', 'dessert')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), LetsCook.core.validators.validate_digits_not_in_string])),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='food-default.png', force_format='JPEG', keep_meta=True, quality=75, size=[680, 382], upload_to='recipes')),
                ('description', models.CharField(max_length=100)),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('servings', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('preparation', models.TextField(max_length=1000)),
                ('vegetarian', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('meal_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='recipes.mealtype')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.FloatField(blank=True)),
                ('measure', models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('pcs', 'pcs')], max_length=20)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
