# Generated by Django 3.2.5 on 2021-08-06 11:48

import LetsCook.core.validators
import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3), LetsCook.core.validators.validate_digits_not_in_string])),
                ('meal_type', models.CharField(choices=[('breakfast', 'breakfast'), ('salad', 'salad'), ('soup', 'soup'), ('appetizer', 'appetizer'), ('main', 'main'), ('dessert', 'dessert')], max_length=20)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.CharField(max_length=100)),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('servings', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('preparation', models.TextField(max_length=1000)),
                ('vegetarian', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('recipe_views', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.FloatField(blank=True, default=0.0, null=True)),
                ('measure', models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('pcs', 'pcs')], default='by taste', max_length=20, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
        ),
    ]
