# Generated by Django 3.2.5 on 2021-08-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('pcs', 'pcs')], default='by taste', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
