# Generated by Django 3.2.5 on 2021-07-08 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210707_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('salad', 'salad'), ('soup', 'soup'), ('main', 'main'), ('dessert', 'dessert'), ('breakfast', 'breakfast')], max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='upload_time',
            new_name='created_on',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measure',
            field=models.CharField(blank=True, choices=[('gr', 'gr'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tea spoon', 'tea spoon'), ('table spoon', 'table spoon'), ('cup', 'cup')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='recipes.mealtype'),
        ),
    ]
