# Generated by Django 3.2.5 on 2021-07-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210708_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtype',
            name='meal_type',
            field=models.CharField(max_length=20),
        ),
    ]
