# Generated by Django 3.2.5 on 2021-07-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealtype',
            old_name='meal_type',
            new_name='name',
        ),
    ]
