# Generated by Django 3.2.5 on 2021-07-11 21:04

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_rename_meal_type_mealtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='food-default.png', force_format='JPEG', keep_meta=True, quality=75, size=[520, 520], upload_to='recipes'),
        ),
    ]
