# Generated by Django 3.2.5 on 2021-07-29 10:52

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_icook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth_icook.icookuser')),
                ('username', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='profile-default.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[200, 200], upload_to='profiles')),
                ('dark_theme', models.BooleanField(default=True)),
            ],
        ),
    ]
