# Generated by Django 3.2.5 on 2021-07-28 10:09

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], default='profile-default.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[200, 200], upload_to='profiles'),
        ),
    ]
