# Generated by Django 3.2.5 on 2021-08-05 13:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default=0, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
